import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MetaMaskWeb3 from "@/Providers/Web3MetaMaskProvider";
import {CustomWagmiProvider} from "@/Providers/CustomWagmiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <MetaMaskWeb3>
        <CustomWagmiProvider>
        {children}
        </CustomWagmiProvider>
        </MetaMaskWeb3>
      </body>
    </html>
  );
}
